### ISSUE TITLE
Invalid copy of GPLv3

### ISSUE THREAD

**Issue by neox95** [Freeloo/BlumenOS#1]
Hi, 
The text you took for your LICENSE file is an invalid copy of the original text : missing spaces, missing titles, etc. 
Please use https://www.gnu.org/licenses/gpl-3.0.txt to create your LICENSE file or use Github to generate a proper one. 
For instance, your current use of that text is illegal.

**Comment by Raxa04** [comment]
c'est mieux dit

**Comment by Freeloo** [comment]
oops, i change that now
