### ISSUE TITLE
Can't reproduce executables, GRUB

### ISSUE THREAD

**Issue by neox95** [Freeloo/BlumenOS#2]
Hi,
There is no Makefile, no GRUB & iso installation script, no way to obtain the same binaries that you provide without more information. 
Which compiler do you use btw ? 

And why are you providing the GRUB source code ? If you haven't modified it there is no need to distribute that code.

**Comment by Freeloo** [comment]
i have found that on osdev.org :
Warning: GNU GRUB, the bootloader, is licensed under the GNU General Public License. Your iso file contains copyrighted material under that license and redistributing it in violation of the GPL constitutes copyright infringement. The GPL requires you publish the source code corresponding to the bootloader. You need to get the exact source package corresponding to the GRUB package you have installed from your distribution, at the time grub-mkrescue is invoked (as distro packages are occasionally updated). You then need to publish that source code along with your ISO to satisfy the GPL. Alternative, you can build GRUB from source code yourself. Clone the latest GRUB git from savannah (do not use their last release from 2012, it's severely out of date). Run autogen.sh, ./configure and make dist. That makes a GRUB tarball. Extract it somewhere, then build GRUB from it, and install it in a isolated prefix. Add that to your PATH and ensure its grub-mkrescue program is used to produce your iso. Then publish the GRUB tarball of your own making along with your OS release. You're not required to publish the source code of your OS at all, only the code for the bootloader that's inside the iso. 

And i know that i must write a makefile etc and i will do it

**Comment by neox95** [comment]
All of that is only mandatory if you actually *include* the grub binary into your repository. 

The GPL is not a dumb license : if you create a program that is used by GNU/Linux, you don't have to publish the GNU and Linux source codes. The same applies to GNU GRUB

**Comment by neox95** [comment]
Actually, a good way to maintain your repo (and a more cleaner way btw) is to **never upload binaries** into that repository. Only provide source and Makefile, with good compilation explanation and just avoid distributing GRUB yourself. You can create a GRUB installation script that use GRUB as it is installed under GNU/Linux. Otherwise, if you really want to distribute binaries, then you must provide the GRUB source code but not in a tar.gz : you must provide a GRUB source folder that the it user can explore easily. 

I didn't realize you distribute binaries, because no one normally do that on a git repo (except with release system), so I now understand why you provide that source code. But tar.gz is not ok, since it is difficult to explore the code inside to verify easily that it is compliant.

**Comment by Freeloo** [comment]
ok
